name: set up Jekyll site on Github pages
on:
    push:
        branches:
            - main 

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: helaili/jekyll-action@2.0.5
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

